use_frameworks!

target 'VKFriends' do
pod 'SwiftyVK', :git => 'https://github.com/WE-St0r/SwiftyVK.git'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage', '~> 3.1'
pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git'
end